In [54]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [55]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [56]:
print(x)

[['0' 666759 846006 1000 621216 224790 1305]
 ['01-04' 2721901 3269865 4000 2363528 906337 5021]
 ['05-09' 3523284 4078603 5500 2929037 1149566 6472]
 ['10-14' 3916377 3906961 5500 2989258 917703 6772]
 ['15-19' 4048364 5537664 5500 4390590 1147074 7208]
 ['20-24' 4838349 6698846 6000 5326401 1372445 7792]
 ['25-29' 4834567 6262120 6000 4913116 1349004 7871]
 ['30-34' 4757909 5584219 6500 4313030 1271189 7528]
 ['35-39' 4734075 5298702 7000 4206056 1092646 7212]
 ['40-44' 6299641 4662696 7000 3763026 899670 6860]
 ['45-49' 6982467 6204254 7000 4912419 1291835 5865]
 ['50-54' 6228119 5145720 7000 4064246 1081474 5876]
 ['55-59' 5424374 4549035 6500 3616027 933008 5553]
 ['60-64' 4708873 4085505 6000 3321383 764122 5245]
 ['65-69' 4154918 3277097 5500 2649382 627715 4680]
 ['70-74' 4909618 2854797 5000 2321663 533134 2932]
 ['75-79' 3299291 2787967 4000 2226625 561342 2897]
 ['80-84' 2327472 1719902 2500 1375064 344838 1606]
 ['85-89' 1339192 728973 1500 585999 142974 1044]
 ['90+' 55944

In [57]:
print(y)

[ 2400  9600 10000  9000  9000  8000  8000  6000  6000  6000  6000  5000
  4000  4000  3000  2000  1000   500   400   100]


In [58]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [59]:
print(x)

[['0' 666759.0 846006.0 1000 621216 224790 1305]
 ['01-04' 2721901.0 3269865.0 4000 2363528 906337 5021]
 ['05-09' 3523284.0 4078603.0 5500 2929037 1149566 6472]
 ['10-14' 3916377.0 3906961.0 5500 2989258 917703 6772]
 ['15-19' 4048364.0 5537664.0 5500 4390590 1147074 7208]
 ['20-24' 4838349.0 6698846.0 6000 5326401 1372445 7792]
 ['25-29' 4834567.0 6262120.0 6000 4913116 1349004 7871]
 ['30-34' 4757909.0 5584219.0 6500 4313030 1271189 7528]
 ['35-39' 4734075.0 5298702.0 7000 4206056 1092646 7212]
 ['40-44' 6299641.0 4662696.0 7000 3763026 899670 6860]
 ['45-49' 6982467.0 6204254.0 7000 4912419 1291835 5865]
 ['50-54' 6228119.0 5145720.0 7000 4064246 1081474 5876]
 ['55-59' 5424374.0 4549035.0 6500 3616027 933008 5553]
 ['60-64' 4708873.0 4085505.0 6000 3321383 764122 5245]
 ['65-69' 4154918.0 3277097.0 5500 2649382 627715 4680]
 ['70-74' 4909618.0 2854797.0 5000 2321663 533134 2932]
 ['75-79' 3299291.0 2787967.0 4000 2226625 561342 2897]
 ['80-84' 2327472.0 1719902.0 2500 1375064 3448

In [60]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = ct.fit_transform(x).toarray()

In [61]:
print(x)

[[1.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  6.667590e+05 8.460060e+05 1.000000e+03 6.212160e+05 2.247900e+05
  1.305000e+03]
 [0.000000e+00 1.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  2.721901e+06 3.269865e+06 4.000000e+03 2.363528e+06 9.063370e+05
  5.021000e+03]
 [0.000000e+00 0.000000e+00 1.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  3.523284e+06 4.078603e+06 5.

In [62]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [63]:
print(y)

[ 5 12 13 11 11 10 10  9  9  9  9  8  7  7  6  4  3  2  1  0]


In [64]:

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [65]:
print(x_train)

[[0.000000e+00 0.000000e+00 1.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  3.523284e+06 4.078603e+06 5.500000e+03 2.929037e+06 1.149566e+06
  6.472000e+03]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 1.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  4.154918e+06 3.277097e+06 5.500000e+03 2.649382e+06 6.277150e+05
  4.680000e+03]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 1.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  4.048364e+06 5.537664e+06 5.

In [66]:
print(x_test)

[[0.000000e+00 0.000000e+00 0.000000e+00 1.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  3.916377e+06 3.906961e+06 5.500000e+03 2.989258e+06 9.177030e+05
  6.772000e+03]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 1.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  3.299291e+06 2.787967e+06 4.000000e+03 2.226625e+06 5.613420e+05
  2.897000e+03]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 1.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  4.834567e+06 6.262120e+06 6.

In [67]:
print(y_train)

[13  6 11  2  9 12  7  5  0  1  9  4  9  7  8 10]


In [68]:
print(y_test)

[11  3 10  9]


In [69]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [70]:
print(x_train)

[[ 0.          0.          1.          0.         -0.25819889 -0.25819889
   0.         -0.25819889 -0.25819889 -0.25819889  0.         -0.25819889
  -0.25819889 -0.25819889 -0.25819889 -0.25819889  0.         -0.25819889
  -0.25819889 -0.25819889 -0.17275176  0.22272911  0.31294522  0.03478154
   0.90080198  0.68198944]
 [ 0.          0.          0.          0.         -0.25819889 -0.25819889
   0.         -0.25819889 -0.25819889 -0.25819889  0.         -0.25819889
  -0.25819889 -0.25819889  3.87298335 -0.25819889  0.         -0.25819889
  -0.25819889 -0.25819889  0.1857584  -0.20354543  0.31294522 -0.15295706
  -0.38016008 -0.04338806]
 [ 0.          0.          0.          0.          3.87298335 -0.25819889
   0.         -0.25819889 -0.25819889 -0.25819889  0.         -0.25819889
  -0.25819889 -0.25819889 -0.25819889 -0.25819889  0.         -0.25819889
  -0.25819889 -0.25819889  0.12527925  0.998719    0.31294522  1.01595444
   0.89468499  0.97991235]
 [ 0.          0.          0.  

In [71]:
print(x_test)

[[ 0.          0.          0.          1.         -0.25819889 -0.25819889
   0.         -0.25819889 -0.25819889 -0.25819889  0.         -0.25819889
  -0.25819889 -0.25819889 -0.25819889 -0.25819889  0.         -0.25819889
  -0.25819889 -0.25819889  0.05036453  0.13144269  0.31294522  0.07520923
   0.33165924  0.80342541]
 [ 0.          0.          0.          0.         -0.25819889 -0.25819889
   0.         -0.25819889 -0.25819889 -0.25819889  0.         -0.25819889
  -0.25819889 -0.25819889 -0.25819889 -0.25819889  1.         -0.25819889
  -0.25819889 -0.25819889 -0.29988831 -0.4636853  -0.40235814 -0.4367632
  -0.54308263 -0.76512248]
 [ 0.          0.          0.          0.         -0.25819889 -0.25819889
   1.         -0.25819889 -0.25819889 -0.25819889  0.         -0.25819889
  -0.25819889 -0.25819889 -0.25819889 -0.25819889  0.         -0.25819889
  -0.25819889 -0.25819889  0.57152148  1.38401512  0.55137967  1.36673772
   1.39035266  1.24828583]
 [ 0.          0.          0.   